// index.js

Page({
	data: {
		test: [{
            "idx": 0,
            "id": "60022",
            "type": "weapon",
            "name": "沉香墨玉",
            "property": "水",
            "divinatory": "坎",
            "icon": "/image/weapon/60022.png",
            "effect": ["水攻水防+5", "造成暴击时，有50%的几率增加60%的暴击伤害，持续5秒，20秒冷却时间。"],
            "effectUpdata": ["水攻水防+25", "造成暴击时，有50%的几率增加120%的暴击伤害，持续5秒，20秒冷却时间。"],
            "tags": ["爆发", "增益"],
            "vipProp": ["闪避率+5% <侯淑彦专属>"],
            "vipRole": 0,
            "lockEffect": ["风攻风防+20", "造成暴击时，有100%的几率增加60%的暴击伤害，持续5秒，20秒冷却时间。", "雷攻雷防+20", "30%几率使全队获得"],
            "baguaIcon": "/image/bagua/icon/bagua_kan.png",
        },
        {
            "idx": 1,
            "id": "60021",
            "type": "weapon",
            "name": "精美法器",
            "property": "水",
            "divinatory": "坎",
            "icon": "/image/weapon/60021.png",
            "effect": ["水攻水防+5", "使用角色技能或普攻时，有12%几率生成一根冰锥攻击敌人，造成100%水攻的伤害"],
            "effectUpdata": ["", ""],
            "tags": ["爆发", "控制"],
            "vipProp": ["水攻+5% <侯淑彦专属>"],
            "vipRole": 0,
            "lockEffect": ["风攻风防+", "生成巨型冰锥会穿透敌人", "雷攻雷防+", "8%几率生成两根冰锥"],
            "baguaIcon": "/image/bagua/icon/bagua_kan.png",
        },
        {
            "idx": 2,
            "id": "60305",
            "type": "weapon",
            "name": "冰晶令",
            "property": "水",
            "divinatory": "坎",
            "icon": "/image/weapon/60305.png",
            "effect": ["水攻水防+5", "每隔10秒，随机冰冻1个目标 （对玩家减速），持续2秒，并造成80%水攻伤害"],
            "effectUpdata": ["", ""],
            "tags": ["控制"],
            "lockEffect": ["风攻风防+", "每隔10秒改为8秒", "雷攻雷防+", "持续2秒改为3秒"],
            "baguaIcon": "/image/bagua/icon/bagua_kan.png",
        },
        {
            "idx": 3,
            "id": "60313",
            "type": "weapon",
            "name": "净水残页",
            "property": "水",
            "divinatory": "坎",
            "icon": "/image/weapon/60313.png",
            "effect": ["水攻水防+5", "受到火系伤害时，冰冻周围敌人3秒（对玩家减速）。10秒内置冷却"],
            "effectUpdata": ["", ""],
            "tags": ["控制"],
            "lockEffect": ["风攻风防+", "10秒改为6秒内置冷却", "雷攻雷防+", "冰冻周围大范围敌人"],
            "baguaIcon": "/image/bagua/icon/bagua_kan.png",
        },
        {
            "idx": 3,
            "id": "60321",
            "type": "weapon",
            "name": "四海瓶",
            "property": "水",
            "divinatory": "坎",
            "icon": "/image/weapon/60321.png",
            "effect": ["水攻水防+5", "击败怪物时，有1.5%几率发现奇门"],
            "effectUpdata": ["", ""],
            "tags": ["探索"],
            "lockEffect": ["风攻风防+", "", "雷攻雷防+", ""],
            "baguaIcon": "/image/bagua/icon/bagua_kan.png",
        },
        {
            "idx": 2,
            "id": "60329",
            "type": "weapon",
            "name": "善水法身",
            "property": "水",
            "divinatory": "坎",
            "icon": "/image/weapon/60329.png",
            "effect": ["水攻水防+5", "水系残影和道具的掉落权重+200%"],
            "effectUpdata": ["", ""],
            "tags": ["控制"],
            "lockEffect": ["风攻风防+", "火系残影和道具的掉落权重-80%", "雷攻雷防+", "掉落权重+200%改为+250%"],
            "baguaIcon": "/image/bagua/icon/bagua_kan.png",
        },
        {
            "idx": 2,
            "id": "60337",
            "type": "weapon",
            "name": "山河社稷图",
            "property": "水",
            "divinatory": "坎",
            "icon": "/image/weapon/60305.png",
            "effect": ["水攻水防+5", "对敌人施加的负面状态的持续时间+20%"],
            "effectUpdata": ["", ""],
            "tags": ["增益"],
            "lockEffect": ["风攻风防+", "水伤加成+", "雷攻雷防+", "风伤加成+"],
            "baguaIcon": "/image/bagua/icon/bagua_kan.png",
        },
        {
            "idx": 2,
            "id": "60505",
            "type": "weapon",
            "name": "精魂·蓝面蛛",
            "property": "水",
            "divinatory": "坎",
            "icon": "/image/weapon/60305.png",
            "effect": ["水攻水防+5", "残影充能加成+12% （水曜日时1.5倍效果）"],
            "effectUpdata": ["", ""],
            "tags": ["增益"],
            "lockEffect": ["风攻风防+", "", "雷攻雷防+", ""],
            "baguaIcon": "/image/bagua/icon/bagua_kan.png",
        },
        {
            "idx": 2,
            "id": "60508",
            "type": "weapon",
            "name": "精魂·天兵",
            "property": "水",
            "divinatory": "坎",
            "icon": "/image/weapon/60305.png",
            "effect": ["水攻水防+5", "水攻+15%", "土攻-20%"],
            "effectUpdata": ["", ""],
            "tags": ["增益"],
            "lockEffect": ["风攻风防+", "土攻-20%改为-14%", "雷攻雷防+", "土攻-20%改为雷攻-20%"],
            "baguaIcon": "/image/bagua/icon/bagua_kan.png",
        },
        {
            "idx": 2,
            "id": "60031",
            "type": "weapon",
            "name": "凤血玉箫",
            "property": "土",
            "divinatory": "艮",
            "icon": "/image/weapon/60305.png",
            "effect": ["土攻土防+5", "使用角色技能或晋攻时，有12%几率触发地震爆炸，对周围敌人造60%土攻伤害"],
            "effectUpdata": ["", ""],
            "tags": ["群攻"],
            "lockEffect": ["雷攻雷防+", "每次爆炸有30％几率再爆炸", "火攻火防+", ""],
            "baguaIcon": "/image/bagua/icon/bagua_gen.png",
        },
        {
            "idx": 2,
            "id": "60032",
            "type": "weapon",
            "name": "八方心饰",
            "property": "土",
            "divinatory": "艮",
            "icon": "/image/weapon/60305.png",
            "effect": ["土攻土防+5", "造成土系伤害时，有20%几率获得可以免疫1次伤害的屏障，持续15秒。15秒内置冷却"],
            "effectUpdata": ["", ""],
            "tags": ["免疫"],
            "lockEffect": ["雷攻雷防+", "", "火攻火防+", ""],
            "baguaIcon": "/image/bagua/icon/bagua_gen.png",
        },
        {
            "idx": 2,
            "id": "60306",
            "type": "weapon",
            "name": "空明油",
            "property": "土",
            "divinatory": "艮",
            "icon": "/image/weapon/60305.png",
            "effect": ["土攻土防+5", "每隔10秒，随机定身1个目标，持续2秒，并造成100%土攻伤害"],
            "effectUpdata": ["", ""],
            "tags": ["控制"],
            "lockEffect": ["雷攻雷防+", "", "火攻火防+", ""],
            "baguaIcon": "/image/bagua/icon/bagua_gen.png",
        },
        {
            "idx": 2,
            "id": "60314",
            "type": "weapon",
            "name": "远古石环",
            "property": "土",
            "divinatory": "艮",
            "icon": "/image/weapon/60305.png",
            "effect": ["土攻土防+5", "受到水系伤害时，闪避率+20%，持续3秒。8秒内置冷却"],
            "effectUpdata": ["", ""],
            "tags": ["闪避"],
            "lockEffect": ["雷攻雷防+", "8秒改为6.5秒内置冷却", "火攻火防+", "造成土系伤害时才有30%几率触发"],
            "baguaIcon": "/image/bagua/icon/bagua_gen.png",
        },
        {
            "idx": 2,
            "id": "60322",
            "type": "weapon",
            "name": "星晨罗盘",
            "property": "土",
            "divinatory": "艮",
            "icon": "/image/weapon/60305.png",
            "effect": ["土攻土防+5", "击败怪物时，有2%几率卜卦次数"],
            "effectUpdata": ["", ""],
            "tags": ["探索"],
            "lockEffect": ["雷攻雷防+", "土曜日时1.5倍效果", "火攻火防+", "卜卦有时5倍几率触发"],
            "baguaIcon": "/image/bagua/icon/bagua_gen.png",
        },
        {
            "idx": 2,
            "id": "60330",
            "type": "weapon",
            "name": "圣土法身",
            "property": "土",
            "divinatory": "艮",
            "icon": "/image/weapon/60305.png",
            "effect": ["土攻土防+5", "受到水系伤害时，闪避率+20%，持续3秒。8秒内置冷却"],
            "effectUpdata": ["", ""],
            "tags": ["闪避"],
            "lockEffect": ["雷攻雷防+", "8秒改为6.5秒内置冷却", "火攻火防+", "掉落权重+200%改为+250%"],
            "baguaIcon": "/image/bagua/icon/bagua_gen.png",
        },
        {
            "idx": 2,
            "id": "60338",
            "type": "weapon",
            "name": "昆仑石",
            "property": "土",
            "divinatory": "艮",
            "icon": "/image/weapon/60305.png",
            "effect": ["土攻土防+5", "承受的火/水/土/风/雷系伤害-12%"],
            "effectUpdata": ["", ""],
            "tags": ["减伤"],
            "lockEffect": ["雷攻雷防+", "水伤减免+10%", "火攻火防+", "土伤减免+10%"],
            "baguaIcon": "/image/bagua/icon/bagua_gen.png",
        },
        {
            "idx": 2,
            "id": "60506",
            "type": "weapon",
            "name": "精魂·印山兽",
            "property": "土",
            "divinatory": "艮",
            "icon": "/image/weapon/60305.png",
            "effect": ["土攻土防+5", "角色技能冷却-6%（土曜日时1.5倍效果）"],
            "effectUpdata": ["", ""],
            "tags": ["增益"],
            "lockEffect": ["雷攻雷防+", "土攻土防+N（月曜日和日曜日时有效）", "火攻火防+", ""],
            "baguaIcon": "/image/bagua/icon/bagua_gen.png",
        },
        {
            "idx": 2,
            "id": "60514",
            "type": "weapon",
            "name": "精魂·位面球",
            "property": "土",
            "divinatory": "艮",
            "icon": "/image/weapon/60305.png",
            "effect": ["土攻土防+5", "土攻+15%", "风攻-20%"],
            "effectUpdata": ["", ""],
            "tags": ["增益"],
            "lockEffect": ["雷攻雷防+", "风攻-20%改为-14%", "火攻火防+", "风攻-20%改为火攻-20%"],
            "baguaIcon": "/image/bagua/icon/bagua_gen.png",
        },
        {
            "idx": 2,
            "id": "60303",
            "type": "weapon",
            "name": "双鱼温玉",
            "property": "治愈",
            "divinatory": "兌",
            "icon": "/image/weapon/60305.png",
            "effect": ["生命值+100", "造成伤害时，恢复12%生命上限的生命值。25秒內置冷却"],
            "effectUpdata": ["", ""],
            "tags": ["恢复"],
            "lockEffect": ["土攻土防+", "25秒改为18秒内置冷却", "防御+", "全队可获得装备效果"],
            "baguaIcon": "/image/bagua/icon/bagua_dui.png",
        },
        {
            "idx": 2,
            "id": "60319",
            "type": "weapon",
            "name": "素色云界旗",
            "property": "治愈",
            "divinatory": "兌",
            "icon": "/image/weapon/60305.png",
            "effect": ["生命值+100", "击败怪物时，有15%几率获得20红魂"],
            "effectUpdata": ["", ""],
            "tags": ["探索"],
            "lockEffect": ["土攻土防+", "卜卦时有100%几率获得五倍红魂", "防御+", "有2%几率召唤一只红魂蜜蜂"],
            "baguaIcon": "/image/bagua/icon/bagua_dui.png",
        },
        {
            "idx": 2,
            "id": "60327",
            "type": "weapon",
            "name": "尊者谕",
            "property": "治愈",
            "divinatory": "兌",
            "icon": "/image/weapon/60305.png",
            "effect": ["生命值+100", "治疗系残影和道具的掉落权重+200%"],
            "effectUpdata": ["", ""],
            "tags": ["探索"],
            "lockEffect": ["土攻土防+", "风系残影和道具的掉落权重-80%", "防御+", "掉落权重+200%改为+250%"],
            "baguaIcon": "/image/bagua/icon/bagua_dui.png",
        },
        {
            "idx": 2,
            "id": "60335",
            "type": "weapon",
            "name": "清净琉璃瓶",
            "property": "治愈",
            "divinatory": "兌",
            "icon": "/image/weapon/60305.png",
            "effect": ["生命值+100", "反弹伤害时，反弹比例额外+20%"],
            "effectUpdata": ["", ""],
            "tags": ["反伤"],
            "lockEffect": ["土攻土防+", "生命值+N%", "防御+", "月曜日时1.5倍效果"],
            "baguaIcon": "/image/bagua/icon/bagua_dui.png",
        },
        {
            "idx": 2,
            "id": "60503",
            "type": "weapon",
            "name": "精魂·木须魔",
            "property": "治愈",
            "divinatory": "兌",
            "icon": "/image/weapon/60305.png",
            "effect": ["生命值+100", "治疗加成+16%"],
            "effectUpdata": ["", ""],
            "tags": ["恢复"],
            "lockEffect": ["土攻土防+", "生命值＋N（月璀日和日耀日时有效）", "防御+", ""],
            "baguaIcon": "/image/bagua/icon/bagua_dui.png",
        },
        {
            "idx": 2,
            "id": "60511",
            "type": "weapon",
            "name": "精魂·山魂灵",
            "property": "治愈",
            "divinatory": "兌",
            "icon": "/image/weapon/60305.png",
            "effect": ["生命值+100", "生命值+25%", "闪避率-20%"],
            "effectUpdata": ["", ""],
            "tags": ["恢复"],
            "lockEffect": ["土攻土防+", "闪避率-20%改为-14%", "防御+", "闪避率-20%改为施加的增益效果时间-20%"],
            "baguaIcon": "/image/bagua/icon/bagua_dui.png",
        },
        {
            "idx": 2,
            "id": "60011",
            "type": "weapon",
            "name": "天光舍利",
            "property": "火",
            "divinatory": "离",
            "icon": "/image/weapon/60305.png",
            "effect": ["火攻火防+5", "使用角色技能或晋攻时，有12%几率触发火焰爆炸，对周围敌人造成60%火攻的伤害"],
            "effectUpdata": ["", ""],
            "tags": ["群伤"],
            "lockEffect": ["土攻土防+", "每次爆炸有30%几率再次爆炸", "风攻风防+", "在周围2个敌人位置发生爆炸"],
            "baguaIcon": "/image/bagua/icon/bagua_li.png",
        },
        {
            "idx": 2,
            "id": "60012",
            "type": "weapon",
            "name": "黑晶",
            "property": "火",
            "divinatory": "离",
            "icon": "/image/weapon/60305.png",
            "effect": ["火攻火防+5", "每隔10秒随机灼烧单个敌人，每2秒造成24%火攻的伤害，持续30秒，可叠加5层"],
            "effectUpdata": ["", ""],
            "tags": ["单体"],
            "lockEffect": ["土攻土防+", "可叠加5层改为8层", "风攻风防+", ""],
            "baguaIcon": "/image/bagua/icon/bagua_li.png",
        },
        {
            "idx": 2,
            "id": "60304",
            "type": "weapon",
            "name": "炎龙吟",
            "property": "火",
            "divinatory": "离",
            "icon": "/image/weapon/60305.png",
            "effect": ["火攻火防+5", "进入每个关卡时，获得2个围绕的火球，每次对敌人造成20%火攻的伤害，持续100秒"],
            "effectUpdata": ["", ""],
            "tags": ["群伤"],
            "lockEffect": ["土攻土防+", "持续100秒改为150秒", "风攻风防+", ""],
            "baguaIcon": "/image/bagua/icon/bagua_li.png",
        },
        {
            "idx": 2,
            "id": "60312",
            "type": "weapon",
            "name": "烈鳌",
            "property": "火",
            "divinatory": "离",
            "icon": "/image/weapon/60305.png",
            "effect": ["火攻火防+5", "受到雷系伤害时，水伤减免和火伤加成+24%，持续4秒。8秒内置冷却"],
            "effectUpdata": ["", ""],
            "tags": ["增益"],
            "lockEffect": ["土攻土防+", "8秒改为6秒内置冷却", "风攻风防+", "造成火系伤害时有30%触发装备效果"],
            "baguaIcon": "/image/bagua/icon/bagua_li.png",
        },
        {
            "idx": 2,
            "id": "60320",
            "type": "weapon",
            "name": "通天神火柱",
            "property": "火",
            "divinatory": "离",
            "icon": "/image/weapon/60305.png",
            "effect": ["火攻火防+5", "击败怪物时，有15%几率获得50战斗经验"],
            "effectUpdata": ["", ""],
            "tags": ["探索"],
            "lockEffect": ["土攻土防+", "火曜日1.5倍几率", "风攻风防+", "效果附加1阴阳币"],
            "baguaIcon": "/image/bagua/icon/bagua_li.png",
        },
        {
            "idx": 2,
            "id": "60328",
            "type": "weapon",
            "name": "灵火法身",
            "property": "火",
            "divinatory": "离",
            "icon": "/image/weapon/60305.png",
            "effect": ["火攻火防+5", "火系残影和道具的掉落权重+200%"],
            "effectUpdata": ["", ""],
            "tags": ["探索"],
            "lockEffect": ["土攻土防+", "雷系残影和道具的掉落权重-80%", "风攻风防+", "掉落权重+200%改为+250%"],
            "baguaIcon": "/image/bagua/icon/bagua_li.png",
        },
        {
            "idx": 2,
            "id": "60336",
            "type": "weapon",
            "name": "真火羽衣",
            "property": "火",
            "divinatory": "离",
            "icon": "/image/weapon/60305.png",
            "effect": ["火攻火防+5", "自身负面状态持续时间-20%"],
            "effectUpdata": ["", ""],
            "tags": ["增益"],
            "lockEffect": ["土攻土防+", "", "风攻风防+", ""],
            "baguaIcon": "/image/bagua/icon/bagua_li.png",
        },
        {
            "idx": 2,
            "id": "60504",
            "type": "weapon",
            "name": "精魂·红面蛛",
            "property": "火",
            "divinatory": "离",
            "icon": "/image/weapon/60305.png",
            "effect": ["火攻火防+5", "暴击率+6%（火曜日时1.5倍效果）"],
            "effectUpdata": ["", ""],
            "tags": ["增益"],
            "lockEffect": ["土攻土防+", "追加火攻火防+N（月曜日、日曜日时有效）", "风攻风防+", "追加暴击率+N（火曜日时2倍效果）"],
            "baguaIcon": "/image/bagua/icon/bagua_li.png",
        },
        {
            "idx": 2,
            "id": "60512",
            "type": "weapon",
            "name": "精魂·阴蛊",
            "property": "火",
            "divinatory": "离",
            "icon": "/image/weapon/60305.png",
            "effect": ["火攻火防+5", "火攻+15%", "水攻-20%"],
            "effectUpdata": ["", ""],
            "tags": ["增益"],
            "lockEffect": ["土攻土防+", "水攻-20%改为-14%", "风攻风防+", "水攻-20%改为风攻-20%"],
            "baguaIcon": "/image/bagua/icon/bagua_li.png",
        },
        {
            "idx": 2,
            "id": "60604",
            "type": "weapon",
            "name": "精魂·火麒麟",
            "property": "火",
            "divinatory": "离",
            "icon": "/image/weapon/60305.png",
            "effect": ["火攻火防+5", "生命值+160"],
            "effectUpdata": ["", ""],
            "tags": ["增益"],
            "lockEffect": ["土攻土防+", "火伤加成+N", "生命值+", "抗暴几率+"],
            "baguaIcon": "/image/bagua/icon/bagua_li.png",
        },
        {
            "idx": 2,
            "id": "60041",
            "type": "weapon",
            "name": "君影草头饰",
            "property": "风",
            "divinatory": "巽",
            "icon": "/image/weapon/60305.png",
            "effect": ["风攻风防+5", "造成伤害时，荻得风御，5秒内每次技能会对周围敌人造成30％风攻的伤害。25秒内置冷却 "],
            "effectUpdata": ["", ""],
            "tags": ["群攻"],
            "lockEffect": ["火攻火防+", "25秒改为18秒内置冷却", "水攻水防+", ""],
            "baguaIcon": "/image/bagua/icon/bagua_xun.png",
        },
        {
            "idx": 2,
            "id": "60042",
            "type": "weapon",
            "name": "舍利金塔",
            "property": "风",
            "divinatory": "巽",
            "icon": "/image/weapon/60305.png",
            "effect": ["风攻风防+5", "受到伤害时，闪避率+20%,持续5秒。25秒内置冷却"],
            "effectUpdata": ["", ""],
            "tags": ["增益"],
            "lockEffect": ["火攻火防+", "", "水攻水防+", ""],
            "baguaIcon": "/image/bagua/icon/bagua_xun.png",
        },
        {
            "idx": 2,
            "id": "60307",
            "type": "weapon",
            "name": "幻风刺",
            "property": "风",
            "divinatory": "巽",
            "icon": "/image/weapon/60305.png",
            "effect": ["风攻风防+5", "造成伤害时，随机1个冷却中的角色技能的冷却时间-2秒。12秒内置冷却"],
            "effectUpdata": ["", ""],
            "tags": ["冷却"],
            "lockEffect": ["火攻火防+", "12秒改为5.6秒内置冷却", "水攻水防+", "随机2个"],
            "baguaIcon": "/image/bagua/icon/bagua_xun.png",
        },
        {
            "idx": 2,
            "id": "60315",
            "type": "weapon",
            "name": "风灵骸骨",
            "property": "风",
            "divinatory": "巽",
            "icon": "/image/weapon/60305.png",
            "effect": ["风攻风防+5", "受到土系伤害，雷伤减免和风伤加成+24%, 持续4秒。8秒内置冷却"],
            "effectUpdata": ["", ""],
            "tags": ["增益"],
            "lockEffect": ["火攻火防+", "8秒改为6秒内置冷却", "水攻水防+", "造成风系伤害时才有30%几率触发装备效果"],
            "baguaIcon": "/image/bagua/icon/bagua_xun.png",
        },
        {
            "idx": 2,
            "id": "60323",
            "type": "weapon",
            "name": "风袋",
            "property": "风",
            "divinatory": "巽",
            "icon": "/image/weapon/60305.png",
            "effect": ["风攻风防+5", "击败怪物时，有2%几率发现被动残影"],
            "effectUpdata": ["", ""],
            "tags": ["探索"],
            "lockEffect": ["火攻火防+", "风曜日时1.5倍几率", "水攻水防+", "发现风系被动残影"],
            "baguaIcon": "/image/bagua/icon/bagua_xun.png",
        },
        {
            "idx": 2,
            "id": "60331",
            "type": "weapon",
            "name": "御风法身",
            "property": "风",
            "divinatory": "巽",
            "icon": "/image/weapon/60305.png",
            "effect": ["风攻风防+5", "风系残影和道具的掉落权重+200%"],
            "effectUpdata": ["", ""],
            "tags": ["探索"],
            "lockEffect": ["火攻火防+", "土系残影和道具的掉落权重-80%", "水攻水防+", "掉落权重+200%改为+250%"],
            "baguaIcon": "/image/bagua/icon/bagua_xun.png",
        },
        {
            "idx": 2,
            "id": "60339",
            "type": "weapon",
            "name": "风蒲团",
            "property": "风",
            "divinatory": "巽",
            "icon": "/image/weapon/60305.png",
            "effect": ["风攻风防+5", "施加的增益效果时间+20%"],
            "effectUpdata": ["", ""],
            "tags": ["增益"],
            "lockEffect": ["火攻火防+", "治疗加成+15%", "水攻水防+", "生命值+8%"],
            "baguaIcon": "/image/bagua/icon/bagua_xun.png",
        },
        {
            "idx": 2,
            "id": "60507",
            "type": "weapon",
            "name": "精魂·食骸虫",
            "property": "风",
            "divinatory": "巽",
            "icon": "/image/weapon/60305.png",
            "effect": ["风攻风防+5", "移速+6%（风曜日时1.5倍效果）"],
            "effectUpdata": ["", ""],
            "tags": ["增益"],
            "lockEffect": ["火攻火防+", "", "水攻水防+", "1.5倍改为2倍"],
            "baguaIcon": "/image/bagua/icon/bagua_xun.png",
        },
        {
            "idx": 2,
            "id": "60515",
            "type": "weapon",
            "name": "精魂·蛭蛙",
            "property": "风",
            "divinatory": "巽",
            "icon": "/image/weapon/60305.png",
            "effect": ["风攻风防+5", "风攻+15%", "雷攻-20%"],
            "effectUpdata": ["", ""],
            "tags": ["增益"],
            "lockEffect": ["火攻火防+", "雷攻-20%改为-14%", "水攻水防+", "雷攻-20%改为水攻-20%"],
            "baguaIcon": "/image/bagua/icon/bagua_xun.png",
        },
        {
            "idx": 2,
            "id": "60601",
            "type": "weapon",
            "name": "精魂·刑天",
            "property": "风",
            "divinatory": "巽",
            "icon": "/image/weapon/60305.png",
            "effect": ["风攻风防+8", "水攻水防+8"],
            "effectUpdata": ["", ""],
            "tags": ["增益"],
            "lockEffect": ["风攻风防+", "风伤加成+10%", "水攻水防+", "水伤加成+10%"],
            "baguaIcon": "/image/bagua/icon/bagua_xun.png",
        },
        {
            "idx": 2,
            "id": "60601",
            "type": "weapon",
            "name": "玉麒麟配饰",
            "property": "雷",
            "divinatory": "震",
            "icon": "/image/weapon/60305.png",
            "effect": ["雷攻雷防+5", "造成伤害时，驱使群雷攻击周围敌人，每道雷电造成80%雷攻的伤害。25秒内置冷却"],
            "effectUpdata": ["", ""],
            "tags": ["群伤"],
            "lockEffect": ["水攻水防+", "25秒改为18秒内置冷却", "土攻土防+", "驱使巨型雷灵造成N%雷攻伤害"],
            "baguaIcon": "/image/bagua/icon/bagua_zhen.png",
        },
        {
            "idx": 2,
            "id": "60052",
            "type": "weapon",
            "name": "天璜项链",
            "property": "雷",
            "divinatory": "震",
            "icon": "/image/weapon/60305.png",
            "effect": ["雷攻雷防+5", "每隔20秒，召标一只巨型雷灵随从，持续15秒，随从继承主人60%的雷系属性"],
            "effectUpdata": ["", ""],
            "tags": ["召唤"],
            "lockEffect": ["水攻水防+", "持续15秒改为20秒", "土攻土防+", "有20％几率额外召唤一个"],
            "baguaIcon": "/image/bagua/icon/bagua_zhen.png",
        },
        {
            "idx": 2,
            "id": "60308",
            "type": "weapon",
            "name": "雷兽钢鬃",
            "property": "雷",
            "divinatory": "震",
            "icon": "/image/weapon/60305.png",
            "effect": ["雷攻雷防+5", "造成伤害时，使伤害地点周围敌人雷攻和雷防-20%，持续5秒。25秒内置冷却"],
            "effectUpdata": ["", ""],
            "tags": ["减防"],
            "lockEffect": ["水攻水防+", "25秒改为18秒内置冷却", "土攻土防+", "持续5秒改为7秒"],
            "baguaIcon": "/image/bagua/icon/bagua_zhen.png",
        },
        {
            "idx": 2,
            "id": "60316",
            "type": "weapon",
            "name": "封雷花印",
            "property": "雷",
            "divinatory": "震",
            "icon": "/image/weapon/60305.png",
            "effect": ["雷攻雷防+5", "受到风系伤害时，所有冷却中的角色技能的冷却时间-5秒。12秒内置冷却"],
            "effectUpdata": ["", ""],
            "tags": ["冷却"],
            "lockEffect": ["水攻水防+", "随机1个冷却中的角色技能的冷却时间-15秒", "土攻土防+", "造成雷系伤害时才有30%几率触发装备效果"],
            "baguaIcon": "/image/bagua/icon/bagua_zhen.png",
        },
        {
            "idx": 2,
            "id": "60324",
            "type": "weapon",
            "name": "五雷轮",
            "property": "雷",
            "divinatory": "震",
            "icon": "/image/weapon/60305.png",
            "effect": ["雷攻雷防+5", "击败怪物时，有1.5%几率发现主动残影"],
            "effectUpdata": ["", ""],
            "tags": ["探索"],
            "lockEffect": ["水攻水防+", "（雷曜日1.5倍几率）", "土攻土防+", "发现雷系主动残影"],
            "baguaIcon": "/image/bagua/icon/bagua_zhen.png",
        },
        {
            "idx": 2,
            "id": "60332",
            "type": "weapon",
            "name": "招雷法身",
            "property": "雷",
            "divinatory": "震",
            "icon": "/image/weapon/60305.png",
            "effect": ["雷攻雷防+5", "雷系残影和道具的掉落权重+200%"],
            "effectUpdata": ["", ""],
            "tags": ["探索2"],
            "lockEffect": ["水攻水防+", "风系残影和道具的掉落权重-80%", "土攻土防+", "掉落权重+200%改为+250%"],
            "baguaIcon": "/image/bagua/icon/bagua_zhen.png",
        },
        {
            "idx": 2,
            "id": "60601",
            "type": "weapon",
            "name": "菡萏阵",
            "property": "雷",
            "divinatory": "震",
            "icon": "/image/weapon/60305.png",
            "effect": ["雷攻雷防+5", "每隔10秒，顺次循环获得攻击/火系/水系/土系/风系/雷系伤害+40%，持续10秒"],
            "effectUpdata": ["", ""],
            "tags": ["增益"],
            "lockEffect": ["水攻水防+", "每隔10秒改为5秒，持续10秒改为5秒", "土攻土防+", "每隔10秒改为20秒，持续10秒改为20秒"],
            "baguaIcon": "/image/bagua/icon/bagua_zhen.png",
        },
        {
            "idx": 2,
            "id": "60508",
            "type": "weapon",
            "name": "精魂·影魂",
            "property": "雷",
            "divinatory": "震",
            "icon": "/image/weapon/60305.png",
            "effect": ["雷攻雷防+5", "暴击伤害+24%（雷曜日时1.5倍效果）"],
            "effectUpdata": ["", ""],
            "tags": ["增益"],
            "lockEffect": ["水攻水防+", "雷攻雷防+N（月曜日和日曜日时有效）", "土攻土防+", "1.5倍改为2倍"],
            "baguaIcon": "/image/bagua/icon/bagua_zhen.png",
        },
        {
            "idx": 2,
            "id": "60516",
            "type": "weapon",
            "name": "精魂·守卫",
            "property": "雷",
            "divinatory": "震",
            "icon": "/image/weapon/60305.png",
            "effect": ["雷攻雷防+5", "雷攻+15%", "火攻-20%"],
            "effectUpdata": ["", ""],
            "tags": ["增益"],
            "lockEffect": ["水攻水防+", "火攻-20%改为-14%", "土攻土防+", "火攻-20%改为土攻-20%"],
            "baguaIcon": "/image/bagua/icon/bagua_zhen.png",
        },
        {
            "idx": 2,
            "id": "60602",
            "type": "weapon",
            "name": "精魂·雷猿",
            "property": "雷",
            "divinatory": "震",
            "icon": "/image/weapon/60305.png",
            "effect": ["雷攻雷防+8", "土攻土防+8"],
            "effectUpdata": ["", ""],
            "tags": ["增益"],
            "lockEffect": ["雷攻雷防+", "雷伤加成+10%", "土攻土防+", "土伤加成+10%"],
            "baguaIcon": "/image/bagua/icon/bagua_zhen.png",
        }
    ]
	},
	onLoad: function () {
		let data = this.data.test
		
		data.map((item,index) => {
			item.idx = index
			item.icon = "/image/weapon/"+ item.id +".png"
			item.effectUpdata = item.effect
		})
		this.setData({
			test:data
		})
	}
})